/**
 * Action types.
 */

export const REQUEST_FLIGHTS_SEARCH = 'REQUEST_FLIGHTS_SEARCH';
export const SEARCH_FLIGHTS = 'SEARCH_FLIGHTS';
export const REQUEST_CITIES = 'REQUEST_CITIES';
export const FETCH_CITIES = 'FETCH_CITIES';
export const UPDATE_FROM = 'UPDATE_FROM';
export const UPDATE_TO = 'UPDATE_TO';
export const UPDATE_DEPART_DATE = 'UPDATE_DEPART_DATE';
export const UPDATE_RETURN_DATE = 'UPDATE_RETURN_DATE';
export const UPDATE_ROUND_TRIP = 'UPDATE_ROUND_TRIP';
export const UPDATE_PASSENGERS = 'UPDATE_PASSENGERS';
export const UPDATE_PRICE_LOW = 'UPDATE_PRICE_LOW';
export const UPDATE_PRICE_HIGH = 'UPDATE_PRICE_HIGH';
